# fly.toml app configuration file generated for wartube2023 on 2023-09-06T18:36:38+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wartube2023"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
